name: Flutter CI

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  distribution: "zulu"
                  java-version: "12.x"
            - uses: subosito/flutter-action@v2
              with:
                  channel: "beta"
            - run: flutter pub get
            - run: flutter build apk --no-tree-shake-icons --release
            - uses: ncipollo/release-action@v1
              with:
                  artifacts: build/app/outputs/apk/release/app-release.apk
                  tag: v1.0.${{ github.run_number }}
                  token: ${{ secrets.TOKEN }}
